// Generated by ../capture/capture.mjs from a real headless Chrome run. Do not edit.
window.HACHIDORI_CAPTURES = {
  "chrome": "Chrome/152.0.7977.75",
  "viewport": {
    "width": 1280,
    "height": 720,
    "deviceScaleFactor": 2
  },
  "dictionaries": [
    {
      "file": "jitendex-yomitan.zip",
      "sha256": "8364e69e7bd0881c42011e96af921a7399d7fe06e2bf4fff4da6d18affff74fc"
    },
    {
      "file": "bees-ultimate-kanji-dictionary.zip",
      "sha256": "e7a75ebdbb8125c71bfda98e3050ba38b00749252e0832a9cc5566a64a260341"
    },
    {
      "file": "bees-ultimate-grammar-dictionary.zip",
      "sha256": "089f496d16549a0392ac46aa4b3192bc77319442cfa102dbcf6b86894e4f58a7"
    },
    {
      "file": "JPDB_v2.2_Frequency_Kana_2024-10-13.zip",
      "sha256": "4fa06c784155ea0ea0953740b99d421296c775ee0d035cfe1ff65a40d7d3e685"
    },
    {
      "file": "kanjium_pitch_accents.zip",
      "sha256": "90d05ad6efc6f44a495bcc01db6b9d3a0f2f1c42ba38adcbefda0ddfaec8b8c2"
    }
  ],
  "importSummary": "Finished 5 of 5 archives — 5 imported, 0 failed.",
  "imports": [
    {
      "file": "jitendex-yomitan.zip",
      "status": "Imported Jitendex.org [2026-08-11] in 1.2 seconds: 435,448 terms, 250 media files."
    },
    {
      "file": "bees-ultimate-kanji-dictionary.zip",
      "status": "Imported Bee's Ultimate Kanji Dictionary in 1.5 seconds: 12,634 terms, 3,897 frequency entries, 10,252 media files."
    },
    {
      "file": "bees-ultimate-grammar-dictionary.zip",
      "status": "Imported Bee's Ultimate Grammar Dictionary in 1.0 seconds: 4,901 terms."
    },
    {
      "file": "JPDB_v2.2_Frequency_Kana_2024-10-13.zip",
      "status": "Imported JPDBv2㋕ in 0.6 seconds: 338,814 frequency entries."
    },
    {
      "file": "kanjium_pitch_accents.zip",
      "status": "Imported Kanjium Pitch Accents in 0.4 seconds: 124,137 pitch entries."
    }
  ],
  "shots": {
    "import-0-empty": {
      "file": "import-0-empty.jpg",
      "pointer": {
        "x": 900,
        "y": 650
      },
      "popups": [],
      "marks": {}
    },
    "import-1-running": {
      "file": "import-1-running.jpg",
      "pointer": {
        "x": 900,
        "y": 650
      },
      "popups": [],
      "marks": {
        "state": {
          "x": 473,
          "y": 228,
          "width": 433,
          "height": 20,
          "inner": {
            "x": 473,
            "y": 228,
            "width": 433,
            "height": 18
          },
          "text": "Importing jitendex-yomitan.zip (1 of 5) — 0 of 5 complete — 0s elapsed"
        }
      }
    },
    "import-2-done": {
      "file": "import-2-done.jpg",
      "pointer": {
        "x": 900,
        "y": 650
      },
      "popups": [],
      "marks": {
        "state": {
          "x": 473,
          "y": 49,
          "width": 284,
          "height": 20,
          "inner": {
            "x": 473,
            "y": 49,
            "width": 284,
            "height": 18
          },
          "text": "Finished 5 of 5 archives — 5 imported, 0 failed."
        },
        "first": {
          "x": 257,
          "y": 147,
          "width": 967,
          "height": 95,
          "inner": {
            "x": 272,
            "y": 160,
            "width": 937,
            "height": 69
          },
          "text": "jitendex-yomitan.zip Yomitan ZIP file Imported Jitendex.org [2026-08-11] in 1.2 seconds: 435,448 terms, 250 media files."
        },
        "firstStatus": {
          "x": 272,
          "y": 210,
          "width": 937,
          "height": 20,
          "inner": {
            "x": 272,
            "y": 210,
            "width": 501,
            "height": 18
          },
          "text": "Imported Jitendex.org [2026-08-11] in 1.2 seconds: 435,448 terms, 250 media files."
        }
      }
    },
    "lookup-0-page": {
      "file": "lookup-0-page.jpg",
      "pointer": {
        "x": 1180,
        "y": 660
      },
      "popups": [],
      "marks": {}
    },
    "lookup-1-popup": {
      "file": "lookup-1-popup.jpg",
      "pointer": {
        "x": 529,
        "y": 300
      },
      "popups": [
        {
          "x": 516,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "word": {
          "x": 516,
          "y": 280,
          "width": 174,
          "height": 40,
          "inner": {
            "x": 516,
            "y": 280,
            "width": 174,
            "height": 40
          },
          "text": "食べたかった"
        },
        "headword": {
          "x": 525,
          "y": 331,
          "width": 84,
          "height": 60,
          "inner": {
            "x": 525,
            "y": 331,
            "width": 84,
            "height": 61
          },
          "text": "食 た べる べ る"
        },
        "deinflection": {
          "x": 525,
          "y": 395,
          "width": 464,
          "height": 19,
          "inner": {
            "x": 525,
            "y": 395,
            "width": 464,
            "height": 257
          },
          "text": "食べたかった → 食べる"
        },
        "stats": {
          "x": 525,
          "y": 430,
          "width": 115,
          "height": 22,
          "inner": {
            "x": 532,
            "y": 432,
            "width": 101,
            "height": 17
          },
          "text": "Looked up 1 time"
        },
        "pitch": {
          "x": 525,
          "y": 457,
          "width": 542,
          "height": 24,
          "inner": {
            "x": 525,
            "y": 457,
            "width": 220,
            "height": 24
          },
          "text": "Kanjium Pitch Accentsたべ る[2]"
        },
        "kanji": {
          "x": 525,
          "y": 356,
          "width": 28,
          "height": 35,
          "inner": {
            "x": 525,
            "y": 352,
            "width": 28,
            "height": 40
          },
          "text": "食"
        }
      }
    },
    "lookup-3-kanji": {
      "file": "lookup-3-kanji.jpg",
      "pointer": {
        "x": 539,
        "y": 373
      },
      "popups": [
        {
          "x": 516,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "back": {
          "x": 940,
          "y": 334,
          "width": 55,
          "height": 32,
          "inner": {
            "x": 949,
            "y": 338,
            "width": 37,
            "height": 24
          },
          "text": "Back"
        },
        "entry": {
          "x": 525,
          "y": 379,
          "width": 542,
          "height": 543,
          "inner": {
            "x": 525,
            "y": 379,
            "width": 542,
            "height": 651
          },
          "text": "Looked up 1 time 77 Bee's Ultimate Kanji Dictionary 食 eat しょく く た eat; food FREQUENCY WEIGHT ■ しょく: 49% ■ く: 31% ■ た: 12% ■ ぐ: 4% ■ Other: 4% 食たべる — to eat 食くう "
        }
      }
    },
    "input-0-page": {
      "file": "input-0-page.jpg",
      "pointer": {
        "x": 1180,
        "y": 660
      },
      "popups": [],
      "marks": {
        "textarea": {
          "x": 208,
          "y": 140,
          "width": 932,
          "height": 120,
          "inner": null,
          "text": ""
        }
      }
    },
    "input-1-popup": {
      "file": "input-1-popup.jpg",
      "pointer": {
        "x": 421,
        "y": 175
      },
      "popups": [
        {
          "x": 409,
          "y": 198,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {
        "textarea": {
          "x": 208,
          "y": 140,
          "width": 932,
          "height": 120,
          "inner": null,
          "text": ""
        },
        "headword": {
          "x": 418,
          "y": 205,
          "width": 86,
          "height": 60,
          "inner": {
            "x": 418,
            "y": 205,
            "width": 86,
            "height": 61
          },
          "text": "楽 た の しみ し み"
        }
      }
    },
    "anki-0-settings": {
      "file": "anki-0-settings.jpg",
      "pointer": {
        "x": 20,
        "y": 700
      },
      "popups": [],
      "marks": {
        "status": {
          "x": 942,
          "y": 199,
          "width": 221,
          "height": 28,
          "inner": {
            "x": 965,
            "y": 204,
            "width": 188,
            "height": 17
          },
          "text": "Connected · configuration ready"
        },
        "find": {
          "x": 1061,
          "y": 286,
          "width": 146,
          "height": 36,
          "inner": {
            "x": 1072,
            "y": 294,
            "width": 124,
            "height": 19
          },
          "text": "Find existing setup"
        }
      }
    },
    "anki-1-mapping": {
      "file": "anki-1-mapping.jpg",
      "pointer": {
        "x": 20,
        "y": 700
      },
      "popups": [],
      "marks": {
        "mapping": {
          "x": 257,
          "y": 0,
          "width": 967,
          "height": 2452,
          "inner": {
            "x": 274,
            "y": 17,
            "width": 933,
            "height": 2471
          },
          "text": "Field mapping Fields mapped in exact Anki model order. Preset Automatic suggestions Kiku Lapis Senren Apply preset Showing 22 fields FIELD NAME MARKERS & TEXT O"
        }
      }
    },
    "anki-2-ready": {
      "file": "anki-2-ready.jpg",
      "pointer": {
        "x": 529,
        "y": 178
      },
      "popups": [
        {
          "x": 516,
          "y": 202,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {
        "mine": {
          "x": 963,
          "y": 237,
          "width": 32,
          "height": 32,
          "inner": {
            "x": 969,
            "y": 243,
            "width": 20,
            "height": 20
          },
          "text": ""
        }
      }
    },
    "anki-4-added": {
      "file": "anki-4-added.jpg",
      "pointer": {
        "x": 979,
        "y": 253
      },
      "popups": [
        {
          "x": 516,
          "y": 202,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {
        "mine": {
          "x": 963,
          "y": 237,
          "width": 32,
          "height": 32,
          "inner": {
            "x": 969,
            "y": 243,
            "width": 20,
            "height": 20
          },
          "text": ""
        },
        "feedback": {
          "x": 525,
          "y": 282,
          "width": 542,
          "height": 32,
          "inner": {
            "x": 534,
            "y": 289,
            "width": 524,
            "height": 18
          },
          "text": "Added note 1700000000000."
        }
      }
    },
    "custom-0-selected": {
      "file": "custom-0-selected.jpg",
      "pointer": {
        "x": 832,
        "y": 300
      },
      "popups": [
        {
          "x": 714,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "word": {
          "x": 777,
          "y": 280,
          "width": 58,
          "height": 40,
          "inner": {
            "x": 777,
            "y": 280,
            "width": 58,
            "height": 40
          },
          "text": "千景"
        },
        "notice": {
          "x": 723,
          "y": 379,
          "width": 542,
          "height": 32,
          "inner": {
            "x": 732,
            "y": 386,
            "width": 281,
            "height": 17
          },
          "text": "No definition found. Add your own with the pencil."
        },
        "pencil": {
          "x": 1233,
          "y": 333,
          "width": 32,
          "height": 32,
          "inner": {
            "x": 1239,
            "y": 339,
            "width": 20,
            "height": 20
          },
          "text": ""
        }
      }
    },
    "custom-1-form": {
      "file": "custom-1-form.jpg",
      "pointer": {
        "x": 1249,
        "y": 349
      },
      "popups": [
        {
          "x": 714,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "form": {
          "x": 723,
          "y": 378,
          "width": 542,
          "height": 260,
          "inner": {
            "x": 732,
            "y": 387,
            "width": 524,
            "height": 242
          },
          "text": "Term Reading Definition Cancel Save"
        }
      }
    },
    "custom-2-typing": {
      "file": "custom-2-typing.jpg",
      "pointer": {
        "x": 1249,
        "y": 349
      },
      "popups": [
        {
          "x": 714,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "form": {
          "x": 723,
          "y": 378,
          "width": 542,
          "height": 260,
          "inner": {
            "x": 732,
            "y": 387,
            "width": 524,
            "height": 242
          },
          "text": "Term Reading Definition Cancel Save"
        }
      }
    },
    "custom-3-typed": {
      "file": "custom-3-typed.jpg",
      "pointer": {
        "x": 1249,
        "y": 349
      },
      "popups": [
        {
          "x": 714,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "form": {
          "x": 723,
          "y": 378,
          "width": 542,
          "height": 260,
          "inner": {
            "x": 732,
            "y": 387,
            "width": 524,
            "height": 242
          },
          "text": "Term Reading Definition Cancel Save"
        },
        "save": {
          "x": 1192,
          "y": 603,
          "width": 64,
          "height": 26,
          "inner": {
            "x": 1210,
            "y": 607,
            "width": 27,
            "height": 17
          },
          "text": "Save"
        }
      }
    },
    "custom-4-saved": {
      "file": "custom-4-saved.jpg",
      "pointer": {
        "x": 1224,
        "y": 616
      },
      "popups": [
        {
          "x": 714,
          "y": 324,
          "width": 560,
          "height": 389.609375
        }
      ],
      "marks": {
        "entry": {
          "x": 723,
          "y": 398,
          "width": 542,
          "height": 90,
          "inner": {
            "x": 723,
            "y": 398,
            "width": 542,
            "height": 90
          },
          "text": "Looked up 1 time Hachidori Custom Dictionary Chikage — the narrator's friend (character name)"
        }
      }
    },
    "blur-0-blurred": {
      "file": "blur-0-blurred.jpg",
      "pointer": {
        "x": 239,
        "y": 178
      },
      "popups": [
        {
          "x": 226,
          "y": 202,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {
        "stats": {
          "x": 235,
          "y": 286,
          "width": 121,
          "height": 22,
          "inner": {
            "x": 242,
            "y": 288,
            "width": 107,
            "height": 17
          },
          "text": "Looked up 3 times"
        },
        "definitions": {
          "x": 245,
          "y": 368,
          "width": 522,
          "height": 351,
          "inner": {
            "x": 245,
            "y": 368,
            "width": 522,
            "height": 351
          },
          "text": "priority form ★ adverbno-adj as usual as always as before as ever still 君きみは相あい変かわらず健けん康こうそうに見みえる。 You look as healthy as ever. forms 相変わらず 相変らず JMdict | Tatoeb"
        }
      }
    },
    "blur-1-revealed": {
      "file": "blur-1-revealed.jpg",
      "pointer": {
        "x": 239,
        "y": 178
      },
      "popups": [
        {
          "x": 226,
          "y": 202,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {
        "stats": {
          "x": 235,
          "y": 286,
          "width": 121,
          "height": 22,
          "inner": {
            "x": 242,
            "y": 288,
            "width": 107,
            "height": 17
          },
          "text": "Looked up 3 times"
        },
        "definitions": {
          "x": 245,
          "y": 368,
          "width": 522,
          "height": 351,
          "inner": {
            "x": 245,
            "y": 368,
            "width": 522,
            "height": 351
          },
          "text": "priority form ★ adverbno-adj as usual as always as before as ever still 君きみは相あい変かわらず健けん康こうそうに見みえる。 You look as healthy as ever. forms 相変わらず 相変らず JMdict | Tatoeb"
        }
      }
    },
    "theme-0-store": {
      "file": "theme-0-store.jpg",
      "pointer": {
        "x": 20,
        "y": 700
      },
      "popups": [],
      "marks": {
        "store": {
          "x": 257,
          "y": 160,
          "width": 416,
          "height": 531,
          "inner": {
            "x": 257,
            "y": 160,
            "width": 1230,
            "height": 517
          },
          "text": "Theme Store Choose a bundled popup layout. More themes can ship with future Hachidori releases. Default The original Hachidori popup, with dictionary tabs, freq"
        },
        "preview": {
          "x": 705,
          "y": 160,
          "width": 519,
          "height": 600,
          "inner": {
            "x": 724,
            "y": 179,
            "width": 481,
            "height": 562
          },
          "text": "Live preview View Scale to fit Actual size Try your popup over a game scene. These are sample entries; click a kanji to try its view. Notes are not saved."
        }
      }
    },
    "theme-default": {
      "file": "theme-default.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "default",
      "label": "Hachidori (default)"
    },
    "theme-bee": {
      "file": "theme-bee.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "bee",
      "label": "Bee's Theme"
    },
    "theme-jl": {
      "file": "theme-jl.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "jl",
      "label": "JL"
    },
    "theme-nazeka": {
      "file": "theme-nazeka.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "nazeka",
      "label": "Nazeka"
    },
    "theme-miku": {
      "file": "theme-miku.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "miku",
      "label": "Miku"
    },
    "theme-girlypop": {
      "file": "theme-girlypop.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "girlypop",
      "label": "Girlypop"
    },
    "theme-catppuccin-mocha": {
      "file": "theme-catppuccin-mocha.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "catppuccin-mocha",
      "label": "Catppuccin Mocha"
    },
    "theme-solarized-light": {
      "file": "theme-solarized-light.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "solarized-light",
      "label": "Solarized Light"
    },
    "theme-dracula": {
      "file": "theme-dracula.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "dracula",
      "label": "Dracula"
    },
    "theme-light": {
      "file": "theme-light.jpg",
      "pointer": {
        "x": 674,
        "y": 243
      },
      "popups": [
        {
          "x": 661,
          "y": 267,
          "width": 560,
          "height": 420
        }
      ],
      "marks": {},
      "theme": "light",
      "label": "Light"
    }
  },
  "anki": {
    "detected": {
      "connection": "Connected · configuration ready",
      "deck": "Mining",
      "model": "Kiku"
    },
    "buttonState": "success",
    "note": {
      "deckName": "Mining",
      "modelName": "Kiku",
      "tags": [
        "hachidori"
      ],
      "fields": {
        "Expression": "約束",
        "ExpressionFurigana": "約束[やくそく]",
        "ExpressionReading": "やくそく",
        "MainDefinition": "(★, Jitendex.org [2026-08-11]) nounsurutransitive promise agreement arrangement one's word contract pact 自分が約束したことはちゃんと実行するように最善を尽くすべきだ。 Yo…",
        "Sentence": "それでも、二人で交わした約束は、まだ諦めていない。",
        "SentenceFurigana": "それでも、二人で交わした約束は、まだ諦めていない。",
        "Picture": "[image]",
        "Glossary": "(★, Jitendex.org [2026-08-11]) nounsurutransitive promise agreement arrangement one's word contract pact 自分が約束したことはちゃんと実行するように最善を尽くすべきだ。 Yo…",
        "PitchPosition": "0",
        "PitchCategories": "heiban",
        "Frequency": "JPDBv2㋕: 644, 38387㋕",
        "FreqSort": "644",
        "MiscInfo": "雨の日の約束 · Hachidori reading sample"
      }
    }
  },
  "themes": {
    "palettes": 42,
    "layouts": [
      "Default",
      "Nazeka",
      "Plain",
      "JL",
      "Bee's Theme"
    ]
  },
  "blocked": [],
  "ankiUnknown": []
};
